/*
 * Inventory API
 *
 * This is a API wromo
 *
 * API version: 1.0.0
 * Contact: info.wromo@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/Ghepes/apis/go"

	sw "./go"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/Ghepes/apis/go"

	sw "github.com/Ghepes/apis/go"

	_ "github.com/Ghepes/apis/go/docs"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
