/*
 * Inventory API
 *
 * This is a API wromo
 *
 * API version: 1.0.0
 * Contact: info.wromo@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type InventoryItem struct {

	Id string `json:"id"`

	Name string `json:"name"`

	ReleaseDate time.Time `json:"releaseDate"`

	Manufacturer *Manufacturer `json:"manufacturer"`
}
