/*
 * Inventory API
 *
 * This is a API wromo
 *
 * API version: 1.0.0
 * Contact: info.wromo@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// post inventory item \"name\" \"homePage\" \"phone\"
type Manufacturer struct {

	Name string `json:"name"`

	HomePage string `json:"homePage,omitempty"`

	Phone string `json:"phone,omitempty"`
}
