openapi: 3.0.0
info:
  title: Inventory API
  description: This is a API wromo
  contact:
    email: info.wromo@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Ghepes/mockapiwromo/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Ghepes
  description: Secured Admin-only calls
- name: ghepes
  description: Operations available to regular developers
paths:
  /inventory:
    get:
      tags:
      - developers
      summary: searches inventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      operationId: search_inventory
      parameters:
      - name: searchString
        in: query
        description: pass an optional search string for looking up inventory
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 50
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InventoryItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.developers_controller
    post:
      tags:
      - admins
      summary: adds an inventory item
      description: Adds an item to the system
      operationId: add_inventory
      requestBody:
        description: Inventory item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryItem'
      responses:
        "201":
          description: item created
        "400":
          description: "invalid input, object invalid"
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.admins_controller
components:
  schemas:
    InventoryItem:
      required:
      - id
      - manufacturer
      - name
      - releaseDate
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter api
        releaseDate:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        manufacturer:
          $ref: '#/components/schemas/Manufacturer'
      example:
        releaseDate: 2016-08-29T09:12:33.001Z
        name: Widget Adapter api
        id: d290f1ee-6c54-4b01-90e6-d701748f0851
        manufacturer:
          phone: 408-867-5309
          name: Studio Wromo Marketplace
          homePage: https://next.wromo.com
    Manufacturer:
      required:
      - name
      type: object
      properties:
        name:
          type: string
          example: Studio Wromo Marketplace
        homePage:
          type: string
          format: url
          example: https://next.wromo.com
        phone:
          type: string
          example: 408-867-5309
      description: post inventory item "name" "homePage" "phone"
      example:
        phone: 408-867-5309
        name: Studio Wromo Marketplace
        homePage: https://next.wromo.com

